name = "worktimer"
version = "0.1.0"
stack = "rust"
atifact_directory = "artifacts"

[[build]]
architecture = "amd64"
platform = "linux"

[[artifact]]
name = "worktimer"
include_checksum = true
path_template = "$(BUILD)/worktimer"
target_name_template = "worktimer-$(PLATFORM)-$(ARCHITECTURE)"
